name: FastApi app Ci/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install --upgrade setuptools wheel
        pip install -r requirements.txt

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
        ssh-keyscan $EC2_HOST >> ~/.ssh/known_hosts
        scp -r . $EC2_USER@$EC2_HOST:/home/$EC2_USER/app
        ssh $EC2_USER@$EC2_HOST << 'EOF'
          cd /home/$EC2_USER/app
          # source venv/bin/activate
          # pip install -r requirements.txt
          # uvicorn main:app --reload --host 0.0.0.0 --port 8000
