name: Build, Push, Deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          ecr: auto
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: phuongto07092000/fastapi:latest
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: [ build_and_push ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          ecr: auto
          logout: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set permissions for private key
        run: |
          echo "${{ env.AWS_PRIVATE_KEY }}" > staging.pem
          chmod 600 staging.pem
      - name: Pull Docker image
        run: |
          ssh -o StrictHostKeyChecking=no -i staging.pem ubuntu@${{ secrets.EC2_HOST }} 'sudo docker pull phuongto07092000/fastapi:latest'
      # - name: Stop running container
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i staging.pem ubuntu@your-ec2-instance-ip 'sudo docker stop fastapi || true'
      #     ssh -o StrictHostKeyChecking=no -i staging.pem ubuntu@your-ec2-instance-ip 'sudo docker rm fastapi || true'
      # - name: Run new container
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -i staging.pem ubuntu@your-ec2-instance-ip 'sudo docker run -d --name fastapi -p 80:3000 phuongto07092000/fastapi:latest'
